name: expenses_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.1.5
  animated_splash_screen: ^1.3.0
  animations: ^2.0.7
  card_swiper: ^2.0.4
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.1.6

  #logic stuff
  flutter_riverpod: ^2.1.1
  tuple: ^2.0.1
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  flutter_lints: ^2.0.0


flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

    flavors:
      development:
        app:
          name: "Expense Tracker Dev"

        android:
          applicationId: "android.dev.ririlya.expensetrackerdemo"

        ios:
          bundleId: "ios.dev.ririlya.expensetrackerdemo"
          #buildSettings:
            # Development Team is visible in the apple developer portal
            #DEVELOPMENT_TEAM: YOURDEVTEAMID
            #PROVISIONING_PROFILE_SPECIFIER: "Dev-ProvisioningProfile"

      staging:
        app:
          name: "Expense Tracker Staging"

        android:
          applicationId: "android.staging.ririlya.expensetrackerdemo"
        ios:
          bundleId: "ios.staging.ririlya.expensetrackerdemo"
          #buildSettings:
            #DEVELOPMENT_TEAM: YOURSTAGINGTEAMID
            #PROVISIONING_PROFILE_SPECIFIER: "Staging-ProvisioningProfile"

      production:
        app:
          name: "Expense Tracker"

        android:
          applicationId: "android.prod.ririlya.expensetrackerdemo"
        ios:
          bundleId: "ios.prod.ririlya.expensetrackerdemo"
          #buildSettings:
            #DEVELOPMENT_TEAM: YOURPRODUCTIONTEAMID
            #PROVISIONING_PROFILE_SPECIFIER: "Production-ProvisioningProfile"


flutter:
  uses-material-design: true

  assets:
    - assets/onboarding/


  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
